random_state: 42
task: "binary_classification"
target: "convert_84m"   # match 7-year horizon

# Feature groups (we'll auto-discover plasma later)
feature_groups:
  demographics: [age_at_baseline, sex_norm]
  plasma: []
  clinical: []

models:
  logistic_regression:
    C: 1.0
    penalty: "l2"
    solver: "lbfgs"
    max_iter: 1000
    class_weight: "balanced"

calibration:
  method: "isotonic"  # or 'platt'

cv:
  strategy: "group_kfold"
  n_splits: 5
  group_column: "subject_id"
  shuffle: true
  random_state: 42
